### ISSUE TITLE
Application crash for MTS video (ffplay is OK)

### ISSUE THREAD

**Issue by nigels-com** [OpenShot/libopenshot#139]
Trying the latest AppImage release a freeze with the video from my Sony Cybershot DSC-WX80 camera. 

The raw files on the memory card are as follows:

```
$ ls -lath /media/nigels/disk/PRIVATE/AVCHD/BDMV/STREAM/
-rw-r--r-- 1 nigels nigels 351M Jun 30 14:21 00009.MTS
...
```
Which both ffmpeg and ffplay seem happy with:

```
$ ffmpeg -i ../src/examples/test.mp4 -hide_banner
Input #0, mpegts, from '../src/examples/test.mp4':
  Duration: 00:02:58.69, start: 1.033367, bitrate: 16438 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:2[0x1200]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090), 1920x1080
At least one output file must be specified
```

OpenShot is happy to import it, but gets stuck in playback.

When I dropped this into the test harness in libopenshot:

```
$ make test
----------------------------
     RUNNING ALL TESTS
----------------------------
[AudioData @ 0x7fb7848318c0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba1860] invalid NULL pointer for src[0]
/data/home/nigels/dev/libopenshot/tests/FFmpegReader_Tests.cpp:82: error: Failure in FFmpegReader_Check_Video_File: Unhandled exception: Crash!
[AudioData @ 0x7ffc0fba1c90] invalid NULL pointer for src[0]
[AudioData @ 0x7fb7848318c0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba1cf0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba1cf0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba1cf0] invalid NULL pointer for src[0]
[libvpx @ 0x2ee6400] v1.5.0
[webm @ 0x2ee5e20] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[AudioData @ 0x7fb7858338c0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba10d0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba13f0] invalid NULL pointer for src[0]
[AudioData @ 0x7ffc0fba13f0] invalid NULL pointer for src[0]
/data/home/nigels/dev/libopenshot/tests/Timeline_Tests.cpp:88: error: Failure in Timeline_Check_Two_Track_Video: Unhandled exception: Crash!
FAILURE: 2 out of 79 tests failed (2 failures).
Test time: 6.19 seconds.
```

I'd be happy to share the google drive link to the file to anyone interested enough to dig deeper.

**Comment by nigels-com** [comment]
A stack dump for the first unit test crash:

```
(gdb) where
#0  0x00007ffff660e177 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00000000004609da in UnitTest::MemoryOutStream::GetText() const ()
#2  0x00000000004324f5 in UnitTest::CheckEqual<int, int> (results=..., expected=@0x7fffffffc90c: 21, actual=@0x7fffffffc910: 104, details=...)
    at /usr/include/unittest++/Checks.h:26
#3  0x000000000043fd17 in TestFFmpegReader_Check_Video_File::RunImpl (this=0x67c120 <testFFmpegReader_Check_Video_FileInstance>)
    at /data/home/nigels/dev/libopenshot/tests/FFmpegReader_Tests.cpp:98
#4  0x000000000045fb22 in void UnitTest::ExecuteTest<UnitTest::Test>(UnitTest::Test&, UnitTest::TestDetails const&) ()
#5  0x00000000004601b5 in UnitTest::TestRunner::RunTest(UnitTest::TestResults*, UnitTest::Test*, int) const ()
#6  0x00000000004605e3 in UnitTest::RunAllTests() ()
#7  0x000000000042970b in main () at /data/home/nigels/dev/libopenshot/tests/tests.cpp:42
(gdb) print stream
$3 = {<std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >> = {<No data fields>}, m_text = ""}
```

**Comment by nigels-com** [comment]
Some handbrake logging for transcoding to m4v for OpenShot purposes...

```
[14:18:12] file is MPEG Transport Stream with 192 byte packets offset 4 bytes
[14:18:12] Found the following PIDS
[14:18:12]     Video PIDS : 
[14:18:12]       0x1011 type H.264 (0x1b)
[14:18:12]     Audio PIDS : 
[14:18:12]       0x1100 type AC3 (0x81)
[14:18:12]     Subtitle PIDS : 
[14:18:12]       0x1200 type PGS Subtitle (0x90)
[14:18:12]     Other PIDS : 
[14:18:12]       0x1001 type Unknown (0xff) (PCR)
[14:18:12] stream id 0x1100 (type 0x81 substream 0x0) audio 0x1100
[14:18:12] stream id 0x1200 (type 0x90 substream 0x0) subtitle 0x1200
[14:18:12] stream doesn't seem to have video IDR frames
[14:18:12] scan: decoding previews for title 1
[14:18:12] file is MPEG Transport Stream with 192 byte packets offset 4 bytes
[14:18:12] scan: audio 0x1100: ac3, rate=48000Hz, bitrate=256000 Unknown (AC3) (2.0 ch)
[14:18:13] stream: 15 good frames, 0 errors (0%)
[14:18:13] scan: 10 previews, 1920x1080, 29.970 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1
[14:18:13] libhb: scan thread found 1 valid title(s)
[14:18:13] starting job
[14:18:13] job configuration:
[14:18:13]  * source
[14:18:13]    + /home/nigels/Downloads/00009.MTS
[14:18:13]    + title 1, chapter(s) 1 to 1
[14:18:13]  * destination
[14:18:13]    + /home/nigels/Videos/00009.m4v
[14:18:13]    + container: MPEG-4 (libavformat)
[14:18:13]  * video track
[14:18:13]    + decoder: h264
[14:18:13]      + bitrate 200 kbps
[14:18:13]    + filters
[14:18:13]      + Framerate Shaper (mode=1)
[14:18:13]        + frame rate: 29.970 fps -> constant 29.970 fps
[14:18:13]      + Crop and Scale (width=1920:height=1080:crop-top=0:crop-bottom=0:crop-left=0:crop-right=0)
[14:18:13]        + source: 1920 * 1080, crop (0/0/0/0): 1920 * 1080, scale: 1920 * 1080
[14:18:13]    + Output geometry
[14:18:13]      + storage dimensions: 1920 x 1080
[14:18:13]      + pixel aspect ratio: 1 : 1
[14:18:13]      + display dimensions: 1920 x 1080
[14:18:13]    + encoder: H.264 (libx264)
[14:18:13]      + preset:  fast
[14:18:13]      + options: keyint=12:min-keyint=1:ref=1:bframes=0:qcomp=0.8:aq-strength=0.5:dct-decimate=0:fast-pskip=0:deblock=-2,-2
[14:18:13]      + profile: high
[14:18:13]      + level:   auto
[14:18:13]      + quality: 2.00 (RF)
[14:18:13]  * audio track 1
[14:18:13]    + decoder: Unknown (AC3) (2.0 ch) (track 1, id 0x1100)
[14:18:13]      + bitrate: 256 kbps, samplerate: 48000 Hz
[14:18:13]    + mixdown: Stereo
[14:18:13]    + encoder: AAC (libavcodec)
[14:18:13]      + bitrate: 320 kbps, samplerate: 48000 Hz
[14:18:13] file is MPEG Transport Stream with 192 byte packets offset 4 bytes
[14:18:13] sync: expecting 5351 video frames
...
````

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Sorry to bother you, sir, but I think you can really get do some great deductions from the information given here. Care to see this, please?
