### ISSUE TITLE
Crash of the latest dev version on Linux Mint 18.3

### ISSUE THREAD

**Issue by cptX** [OpenShot/libopenshot#81]
```
$ openshot-qt
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.4.1.dev1', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
      logger:ERROR return get_distribution(dist).load_entry_point(group, name)
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
      logger:ERROR return ep.load()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
      logger:ERROR return self.resolve()
      logger:ERROR   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
      logger:ERROR module = __import__(self.module_name, fromlist=['__name__'], level=0)
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 41, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 28, in <module>
      logger:ERROR _openshot = swig_import_helper()
      logger:ERROR   File "/usr/lib/python3/dist-packages/openshot.py", line 24, in swig_import_helper
      logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 242, in load_module
      logger:ERROR return load_dynamic(name, filename, file)
      logger:ERROR   File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
      logger:ERROR return _load(spec)
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR /usr/lib/python3/dist-packages/_openshot.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVN8openshot10ColorShiftE
```

After crash openshot cannot start again, even after restart. Uninstalled it and installed the stable ppa and the corresponding openshot-qt but still the application cannot start. What happened. How can I solve the problem?

(2019-07-11: Original comment edited to fence program output for readability. – @ferdnyc)

**Comment by peanutbutterandcrackers** [comment]
This is strange. OpenShot works just fine on my friend's Linux Mint 18.3 laptop. But we're using the daily PPA instead of the latest stable one. Perhaps you might want to consider switching to the daily PPA, too?
Hope that helps!

**Comment by ferdnyc** [comment]
I'm going to close this since it was reported against 2.4.1, and OpenShot 2.4.4 is the current version. I think it's safe to assume _this_ issue is no longer occurring. (There are probably other issues, _new_ issues, but those can go into new reports.)
